language: node_js
node_js:
- '8'
services:
- mongodb
notifications:
  slack: botfuel:m19mrLajAVq0CkYHceYCGnL9
script:
- npm run style
- npm test
after_success:
- bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
