language: node_js
node_js:
- '8'
services:
- mongodb
env:
  global:
    secure: fsLBBN2j+zfzZJyMREW3yPAN0VXhYnwep3MTzGzIMdGBeepmAji0vASFd6T1bCilhhH7378ueaSK4b4jCnn2/Cy6L05TA+zt8KJj5iccHcP8tshzsCY1ZtPy1CYn5O4vVGxM0mNyZjXgTpAevPL6HjkbSFWgeApDz+Q2gUyvuk6ndeDr5gbF/Js70KmZIe2uSA8TpT0calRJNHlD+T0KlG5+LpVlk9j+KRwDr1o/0jxzA44SziPr14B+ediyaeQfsKbIp9KREf93y9TXX6EKH+DinR70r4dCeJDQwWNesltocA8wSzXDU+Ll8iHXLdqF4j7pxmaYy9hAM1xHfNTnQ4yLUItynL9j8y45MncJwDYjrvATblodBuYxQn4v+1Os7PooSLOYLlqX+YZGfNOoE8hZ3u+8GWg+fTMToSH/nj460yFwlLa8BZ58Cq0BgyLA1AVLJneBhIcOpNZ5pwA4hjGe1it8vjhrGiWuGNGRJlVlwYAKbCvlTA8tIn04h2CSQlOeY/9vudK440UBZ2bXfJmXlz/DpXPutHFfwEJIesqWjJCH8LanfugTp/dQW8BwFg7XAuHHi5Y0Zsh/TdRyD3Jn57Z8md9NRwiSV5PxyPmFDslZ068eYc9ocboFo5Uw4ld6CfbCTai1cj3d6SFpbPLsk2wxxVvpjg4qH2CHlSM=
notifications:
  slack: botfuel:m19mrLajAVq0CkYHceYCGnL9
script:
- npm run style
- npm test
after_success:
- bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
