version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-jessie
      - image: circleci/mongo:3.6-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Bootstrap botfuel-dialog
          command: npm run bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Check code style
          command: npm run style
      - run:
          name: Run tests
          command: jest --runInBand
      - run:
          name: Generate Codecov report
          command: bash <(curl -s https://codecov.io/bash)
