version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.10.0
      - image: circleci/mongo:3.6.9
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm run bootstrap
      - save_cache:
          paths:
            - node_modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run style
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)
